### ISSUE TITLE
2.0.0 example-web Broken

### ISSUE THREAD

**Issue by pokkie** [camunda/camunda-bpm-spring-boot-starter#183] opened 2016-12-10 16:15 UTC
2016-12-10 18:09:43.098  WARN 8742 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Dbcp.class]: Unsatisfied dependency expressed through method 'dataSource' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'processEngineFactoryBean' defined in class path resource [org/camunda/bpm/spring/boot/starter/CamundaBpmAutoConfiguration.class]: Unsatisfied dependency expressed through method 'processEngineFactoryBean' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'processEngineConfigurationImpl' defined in class path resource [org/camunda/bpm/spring/boot/starter/CamundaBpmConfiguration.class]: Unsatisfied dependency expressed through method 'processEngineConfigurationImpl' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'camundaDatasourceConfiguration': Unsatisfied dependency expressed through field 'transactionManager'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration$DataSourceTransactionManagerConfiguration': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'dataSource': Requested bean is currently in creation: Is there an unresolvable circular reference?
2016-12-10 18:09:43.101  INFO 8742 --- [           main] o.apache.catalina.core.StandardService   : Stopping service Tomcat
2016-12-10 18:09:43.115  WARN 8742 --- [           main] o.s.boot.SpringApplication               : Error handling failed (Error creating bean with name 'delegatingApplicationListener' defined in class path resource [org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.class]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'org.springframework.context.annotation.ConfigurationClassPostProcessor.importRegistry' available)
2016-12-10 18:09:43.120 ERROR 8742 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

The dependencies of some of the beans in the application context form a cycle:

┌─────┐
|  dataSource defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Dbcp.class]
↑     ↓
|  processEngineFactoryBean defined in class path resource [org/camunda/bpm/spring/boot/starter/CamundaBpmAutoConfiguration.class]
↑     ↓
|  processEngineConfigurationImpl defined in class path resource [org/camunda/bpm/spring/boot/starter/CamundaBpmConfiguration.class]
↑     ↓
|  camundaDatasourceConfiguration (field protected org.springframework.transaction.PlatformTransactionManager org.camunda.bpm.spring.boot.starter.configuration.impl.DefaultDatasourceConfiguration.transactionManager)
↑     ↓
|  org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration$DataSourceTransactionManagerConfiguration
└─────┘

**Comment by jangalinski** [comment] 2016-12-14 08:26
Thanks for using the extension and making it better by raising issues! But I am missing the context here ... what are you trying to do, what leads to this stacktrace?

**Comment by jangalinski** [comment] 2016-12-14 08:27
Migt this be related to #148? I fixed that by adding the `@EnableProcessApplication` annotation to the spring app.

**Comment by jangalinski** [comment] 2016-12-19 10:18
Since jenkins is building correctly, I am going to close this soon with "cannot reproduce". Unless you could give me a hint what leads to the problems.

**Comment by pokkie** [comment] 2016-12-19 10:45
Hi, 

Apologies for the late reply. 

As soon as I check out the code (2.0.0 tag) and I follow the instructions, then the I get the stack trace that I posted.

**Comment by pokkie** [comment] 2016-12-19 10:48
Have you tried checking and running the example-web application in the 2.0.0 tag?

**Comment by jangalinski** [comment] 2016-12-19 10:51
The example-web was my test application to manually verify all implemented features work in "real life" ... so basically: yes. But I will try again with the tag to verify.

**Comment by Zapata** [comment] 2016-12-23 16:04
I  confirm example-web is broken on master ([2007cd](https://github.com/camunda/camunda-bpm-spring-boot-starter/commit/2007cdef03607bcd47dccde9b25acc2c284f87e3)). Unit test are ok, but main fails as reported.  I fixed it adding `@EnableProcessApplication` on `RestApplication` as suggested.

**Comment by jangalinski** [comment] 2016-12-29 08:40
Hi pokkie, sorry for the confusion ... I did not run example-web but example-webapp ... I will rename this one to example-rest ....     Adding the annotation like zapata suggested helps with running the app and building with maven, but I get an error when running all tests in IDEA ... will have to think about it, keep you posted.

Jan

**Comment by pokkie** [comment] 2017-01-03 05:59
@jangalinski @Zapata thanks for the feedback.

**Comment by jangalinski** [comment] 2017-02-10 16:17
have to reopen ... this is highly unstable ... with this fix, the webapp runs, but the IT fails ... without it, the IT runs and the webapp fails ... 💢

**Comment by jangalinski** [comment] 2017-04-26 07:48
Might be fixed with 2.1.0, have to evaluate

**Comment by osteinhauer** [comment] 2017-04-30 09:01
should be fixed with #242? is #242 a duplicated of this? if so, my fault. sorry.

**Comment by jangalinski** [comment] 2017-04-30 09:02
no 242 does more

**Comment by osteinhauer** [comment] 2017-04-30 09:17
ok, but imho #148 and #183 where bugs related to the auto configuration resolved in #242.

**Comment by jangalinski** [comment] 2017-04-30 11:38
so can this be closed?

**Closed** 2017-04-30 11:40 UTC
Labels: bug
