### ISSUE TITLE
Auto-Deployment fails on Spring-Boot 1.4.1

### ISSUE THREAD

**Issue by mufasa1976** [camunda/camunda-bpm-spring-boot-starter#154] opened 2016-10-20 17:17 UTC
Hi!

Unfortunatly the Auto-Deployment fails with camunda-bpm-spring-boot-starter 1.3.0 and Spring-Boot 1.4.1 because Spring-Boot doesn't find ClassPath Resources.

my application.yaml File

```
...
camunda.bpm:
  deployment-resource-pattern:
  - classpath:/bpmn/**/*.bpmn
...
```

I used the spring-boot-maven-plugin to repackage my Application as a executable JAR-Archive which resides inside a Docker-Image.

On Application Startup the following Error occurs:

```
java.io.FileNotFoundException: class path resource [bpmn/acmeProcess.bpmn] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/opt/acme.core.command.server.jar!/BOOT-INF/classes!/bpmn/acmeProcess.bpmn
         at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:218) ~[spring-core-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
         at org.springframework.core.io.AbstractFileResolvingResource.getFile(AbstractFileResolvingResource.java:52) ~[spring-core-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
         at org.camunda.bpm.spring.boot.starter.configuration.impl.DefaultDeploymentConfiguration.isFile(DefaultDeploymentConfiguration.java:61) [camunda-bpm-spring-boot-starter-1.3.0.jar!/:1.3.0]
         at org.camunda.bpm.spring.boot.starter.configuration.impl.DefaultDeploymentConfiguration.getDeploymentResources(DefaultDeploymentConfiguration.java:37) [camunda-bpm-spring-boot-starter-1.3.0.jar!/:1.3.0]
         at org.camunda.bpm.spring.boot.starter.configuration.impl.DefaultDeploymentConfiguration.preInit(DefaultDeploymentConfiguration.java:22) [camunda-bpm-spring-boot-starter-1.3.0.jar!/:1.3.0]

```

I already brought the BPMN-File to the outmost Package. So the BPMN-Files resist within the repackaged JAR-File on the following Position (Output of `jar -tf acme.jar`):

```
...
BOOT-INF/classes/banner.txt
BOOT-INF/classes/bpmn/acmeProcess.bpmn
...
```

Is there any way to tell the Auto-Deployment to use the Resources on the Classpath?
Thank you & best regards,
mufasa1976

**Comment by mufasa1976** [comment] 2016-10-21 09:26
So, after some investigation I've found a solution.

Reason:
With Version 1.4 of the spring-boot-maven-plugin the created JAR-File will no longer put the Files directly under the root of the JAR-Archive. Instead all Classes and Resources will be put under the Directory `/BOOT-INF/classes`, all Libraries unter `/BOOT-INF/lib`.

File Structure of a 1.3 SpringBoot generated JAR-Archive:
```
...
/at/acme/acmeApplication.class
/bpmn/acmeProcess.bpmn
...
/lib/camunda-bpm-spring-boot-starter-1.3.0.jar
...
```

File Structure of a 1.4 SpringBoot generated JAR-Archive:
```
...
/BOOT-INF/classes/at/acme/acmeApplication.class
/BOOT-INF/classes/bpmn/acmeProcess.bpmn
...
/BOOT-INF/lib/camunda-bpm-spring-boot-starter-1.3.0.jar
...
```

Because of the a Spring-Context `ClassPathResource` would no longer has the behaviour of a `FileSystemResource`. Instead this `ClassPathResource` has a similar behaviour as a `UrlResource`.

So I've overridden the `DefaultDeploymentConfiguration` with this Code:
```java
package at.acme.config.camunda;



import java.io.IOException;
import java.net.URL;
import java.util.HashSet;
import java.util.Set;

import org.camunda.bpm.spring.boot.starter.configuration.impl.DefaultDeploymentConfiguration;
import org.springframework.core.io.ClassPathResource;
import org.springframework.core.io.Resource;
import org.springframework.core.io.UrlResource;
import org.springframework.core.io.support.ResourceArrayPropertyEditor;
import org.springframework.stereotype.Service;

import lombok.extern.slf4j.Slf4j;


@Service
@Slf4j
public class DeploymentConfiguration extends DefaultDeploymentConfiguration {

    @Override
    protected Resource[] getDeploymentResources() {

        final Set<Resource> resources = new HashSet<Resource>();
        final ResourceArrayPropertyEditor resolver = new ResourceArrayPropertyEditor();

        try {
            final String[] resourcePattern = camundaBpmProperties.getDeploymentResourcePattern();
            log.debug("resolving deployment resources for pattern {}", (Object[]) resourcePattern);
            resolver.setValue(resourcePattern);

            for (Resource resource : (Resource[]) resolver.getValue()) {
                log.debug("processing deployment resource {}", resource);
                if (isFile(resource)) {
                    resources.add(resource);
                    log.debug("added deployment resource {}", resource);
                }
            }

            log.debug("resolved {}", resources);
        } catch (RuntimeException e) {
            log.error("unable to resolve resources", e);
        }
        return resources.toArray(new Resource[resources.size()]);
    }



    private boolean isFile(Resource resource) {

        if (resource.isReadable()) {
            if (resource instanceof UrlResource || resource instanceof ClassPathResource) {
                try {
                    URL url = resource.getURL();
                    return !url.toString().endsWith("/");
                } catch (IOException e) {
                    log.debug("unable to handle " + resource + " as URL", e);
                }
            } else {
                try {
                    return !resource.getFile().isDirectory();
                } catch (IOException e) {
                    log.debug("unable to handle " + resource + " as file", e);
                }
            }
        }
        log.warn("unable to determine if resource {} is a deployable resource", resource);
        return false;
    }
}
```

It's just like the original `DefaultDeploymentConfiguration` but the `ClassPathResource` will have a behaviour like a `UrlResource` (therefor I'll check both within the if-Block).

This also helps in a Maven multimodule Project, where you have packaged the BPMN-Files within a submodule. Because there will be a JAR in a JAR this solution also helps.

**Comment by jangalinski** [comment] 2016-10-21 09:38
Thanks for analysing ... for some time now, I propagate not to use the autoDeployment feature but instad use a plain "old school" camunda deployment with processes.xml and SpringBootProcessApplication. 

We ran into some issues with the autodeployment (embedded forms do not work, we have to manually keep up with supported file types, and so on) ... I tend to deprecate this with 2.0.0 and focus on the new behavior. I also have some ideas how we can get rid of teh processes.xml and configure it via yaml, but that requires a change in the platform-core that hopefully I can provide before 7.6 ...

**Comment by jangalinski** [comment] 2016-12-08 11:12
I created an example "example-autodeployment" for this but was not able to reproduce it ... nonetheless I included the change. 

One thin is strange: when I run the application via `java -jar ...`, multiple URLs for the same process are found. However it is deployed only once and the assert succeeds.

But meanwhile we use spring boot 1.4.2 ... maybe there was a fix?

```
2016-12-08 12:04:37.245  INFO 7172 --- [           main] org.camunda.bpm.spring.boot              : STARTER-SB021 Auto-Deploying resources: [URL [jar:file:examples/example-autodeployment/target/camunda-bpm-spring-boot-starter-example-autodeployment-2.0.0-SNAPSHOT.jar!/BOOT-INF/classes/bpmn/sample.bpmn], URL [jar:file:/Users/.../camunda-bpm-spring-boot-starter/examples/example-autodeployment/target/camunda-bpm-spring-boot-starter-example-autodeployment-2.0.0-SNAPSHOT.jar!/BOOT-INF/classes/bpmn!/sample.bpmn], URL [jar:file:/.../camunda-bpm-spring-boot-starter/examples/example-autodeployment/target/camunda-bpm-spring-boot-starter-example-autodeployment-2.0.0-SNAPSHOT.jar!/BOOT-INF/classes/bpmn/sample.bpmn], URL [jar:file:/.../camunda-bpm-spring-boot-starter/examples/example-autodeployment/target/camunda-bpm-spring-boot-starter-example-autodeployment-2.0.0-SNAPSHOT.jar!/BOOT-INF/classes!/bpmn/sample.bpmn]]

```

I will close this for now. Please test and open a follow up if there are still problems remaining.

**Closed** 2016-12-08 11:16 UTC

**Comment by mufasa1976** [comment] 2016-12-08 11:30
Many thanks. Unfortunatly I will no longer be able to test it because i left the work where Camunda has been needed. But I will follow the Camunda Project because I am convinced about Camunda that this is a very powerful and lightweigt Workflow Engine. So if I am able to test the Code with Camunda Spring-Boot-Starter 2.0.0 then I will let you know about the results. Best regards, Mufasa1976
