### ISSUE TITLE
Allow configuration of Camunda Webapp base path

### ISSUE THREAD

**Issue by berndruecker** [camunda/camunda-bpm-spring-boot-starter#153] opened 2016-10-11 13:47 UTC
It should be allowed to configure/change the base path. Currently the Webapp is automatically always bound to /app/*.

**Comment by berndruecker** [comment] 2016-10-11 13:49
I actually tried to change this behavior hard coded in the camunda-bpm-spring-boot-starter-webapp - but failed. Whenever I change the mappings there - nothing is working any more.

Either there is still some hard coded piece anywhere I haven't found yet (or some weird code expecting to have the same mapping than path in the webjar?).

Or somehow Spring needs the mapping to be the path in the webjar.
Or?

Anybody can shed some light on this?

**Comment by jangalinski** [comment] 2016-10-11 14:24
I will close this, because its a duplicate of #150.

I think what you are looking for is https://github.com/camunda/camunda-bpm-spring-boot-starter/blob/master/extension/starter-webapp/src/main/java/org/camunda/bpm/spring/boot/starter/webapp/CamundaBpmWebappAutoConfiguration.java

```
@Override
  public void addResourceHandlers(ResourceHandlerRegistry registry) {
    registry.addResourceHandler("/lib/**").addResourceLocations("classpath:/lib/");
    registry.addResourceHandler("/api/**").addResourceLocations("classpath:/api/");
    registry.addResourceHandler("/app/**").addResourceLocations("classpath:/app/");
    super.addResourceHandlers(registry);
  }

  @Override
  public void addViewControllers(ViewControllerRegistry registry) {
    if (isIndexRedirectEnabled) {
      registry.addRedirectViewController("/", "/app/");
    }
    super.addViewControllers(registry);
  }
```

**Closed by jangalinski** 2016-10-11 14:24 UTC

**Comment by berndruecker** [comment] 2016-10-11 14:26
Agreed on the duplicate. Not agreed on the code snippet - that's exactly what I tried and it does not work
